FROM althack/ros2:iron-full

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y --fix-missing\
    ros-iron-xacro ros-iron-image-view ros-iron-foxglove-bridge\
    ros-iron-compressed-image-transport ros-iron-pointcloud-to-laserscan\
    ros-iron-slam-toolbox